### ISSUE TITLE
how to train or test on the release code?

### ISSUE THREAD

**Issue by 10183308** [vikrant7/mobile-vod-bottleneck-lstm#1]
First thank you for your share code.

Could show same documets to guide us how to use the release code?

Thank you for your contribution .

**Comment by vikrant7** [comment]
The implementation is still in progress. I will update the README once I release the full implementation.

**Comment by 10183308** [comment]
@vikrant7 thank you very much, look forward your release.

**Comment by vikrant7** [comment]
I have updated all the details on README.
Please have a look at the same.
