### ISSUE TITLE
Erorr in train_mvod_lstm2

### ISSUE THREAD

**Issue by AmitYadu** [vikrant7/mobile-vod-bottleneck-lstm#16]
2020-02-12 11:40:16,745 - root - INFO - Use Cuda.
2020-02-12 11:40:16,745 - root - INFO - Namespace(base_net_lr=None, batch_size=10, cache_path=None, checkpoint_folder='models/', datasets='./datasets/ILSVRC2015/', debug_steps=100, freeze_net=True, gamma=0.1, lr=0.0003, milestones='80,100', momentum=0.9, num_epochs=30, num_workers=4, pretrained='./models/lstm1/WM-1.0-Epoch-29.pth', resume=None, scheduler='multi-step', sequence_length=10, ssd_lr=None, t_max=120, use_cuda=True, validation_epochs=5, weight_decay=0.0005, width_mult=1.0)
2020-02-12 11:40:16,746 - root - INFO - Prepare training datasets.
class
2020-02-12 11:40:16,748 - root - INFO - using default Imagenet VID classes.
2020-02-12 11:40:16,805 - root - INFO - gt roidb loaded from datasets/ILSVRC2015/train_VID_seq_gt_db.pkl
2020-02-12 11:40:16,807 - root - INFO - Stored labels into file models/vid-model-labels.txt.
2020-02-12 11:40:16,807 - root - INFO - Train dataset size: 330
2020-02-12 11:40:16,807 - root - INFO - Prepare Validation datasets.
class
2020-02-12 11:40:16,808 - root - INFO - using default Imagenet VID classes.
2020-02-12 11:40:16,809 - root - INFO - gt roidb loaded from datasets/ILSVRC2015/val_VID_seq_gt_db.pkl
2020-02-12 11:40:16,809 - root - INFO - <datasets.vid_dataset_new.VIDDataset object at 0x7ff3717af0f0>
2020-02-12 11:40:16,809 - root - INFO - validation dataset size: 0
2020-02-12 11:40:16,809 - root - INFO - Build network.
2020-02-12 11:40:16,825 - root - INFO - Initializing weights of base net
2020-02-12 11:40:16,843 - root - INFO - Initializing weights of lstm
2020-02-12 11:40:19,735 - root - INFO - Initializing weights of lstm
2020-02-12 11:40:19,740 - root - INFO - Initializing weights of ssd
2020-02-12 11:40:19,750 - root - INFO - Loading weights from pretrained netwok
Traceback (most recent call last):
  File "train_mvod_lstm2.py", line 242, in <module>
    initialize_model(net)
  File "train_mvod_lstm2.py", line 202, in initialize_model
    net.load_state_dict(model_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MobileVOD:
	size mismatch for pred_decoder.fmaps_2.0.weight: copying a param with shape torch.Size([64, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 64, 1, 1]).
	size mismatch for pred_decoder.fmaps_2.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for pred_decoder.fmaps_2.2.0.weight: copying a param with shape torch.Size([64, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 1, 3, 3]).
	size mismatch for pred_decoder.fmaps_2.2.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for pred_decoder.fmaps_2.2.2.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 32, 1, 1]).
	size mismatch for pred_decoder.fmaps_2.2.2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.fmaps_3.0.weight: copying a param with shape torch.Size([64, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 64, 1, 1]).
	size mismatch for pred_decoder.fmaps_3.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for pred_decoder.fmaps_3.2.0.weight: copying a param with shape torch.Size([64, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 1, 3, 3]).
	size mismatch for pred_decoder.fmaps_3.2.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for pred_decoder.fmaps_3.2.2.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 32, 1, 1]).
	size mismatch for pred_decoder.fmaps_3.2.2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.fmaps_4.0.weight: copying a param with shape torch.Size([32, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 64, 1, 1]).
	size mismatch for pred_decoder.regression_headers.2.0.weight: copying a param with shape torch.Size([256, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
	size mismatch for pred_decoder.regression_headers.2.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.regression_headers.2.2.weight: copying a param with shape torch.Size([24, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 64, 1, 1]).
	size mismatch for pred_decoder.regression_headers.3.0.weight: copying a param with shape torch.Size([128, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
	size mismatch for pred_decoder.regression_headers.3.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.regression_headers.3.2.weight: copying a param with shape torch.Size([24, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 64, 1, 1]).
	size mismatch for pred_decoder.regression_headers.4.0.weight: copying a param with shape torch.Size([128, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
	size mismatch for pred_decoder.regression_headers.4.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.regression_headers.4.2.weight: copying a param with shape torch.Size([24, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 64, 1, 1]).
	size mismatch for pred_decoder.classification_headers.2.0.weight: copying a param with shape torch.Size([256, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
	size mismatch for pred_decoder.classification_headers.2.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.classification_headers.2.2.weight: copying a param with shape torch.Size([186, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([186, 64, 1, 1]).
	size mismatch for pred_decoder.classification_headers.3.0.weight: copying a param with shape torch.Size([128, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
	size mismatch for pred_decoder.classification_headers.3.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.classification_headers.3.2.weight: copying a param with shape torch.Size([186, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([186, 64, 1, 1]).
	size mismatch for pred_decoder.classification_headers.4.0.weight: copying a param with shape torch.Size([128, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
	size mismatch for pred_decoder.classification_headers.4.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for pred_decoder.classification_headers.4.2.weight: copying a param with shape torch.Size([186, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([186, 64, 1, 1]).

**Comment by hebangwen** [comment]
Hi, how do you solve it? I find that the `fmaps_2` isn't the same between `mvod_bottleneck_lstm1.py` and `mvod_bottleneck_lstm2.py`.
