### ISSUE TITLE
Is it necessary to re-initilize hidden state and cell state after detach_() ?

### ISSUE THREAD

**Issue by turboxin** [vikrant7/mobile-vod-bottleneck-lstm#6]
Hi @vikrant7 , thanks for this great implementation, I have learned a lot from it.

After each iteration of a sequence, you detach the hidden state and cell state of  the lstm cell from the graph to cut backpropagation, do you think it's also necessary to re-initilize them, since hidden state and cell state should be zero for the start of a new sequence?

**Comment by vikrant7** [comment]
Hi @turboxin, 
Why do you think the cell state and hidden state should be zero at the starting of the sequence?
I will suggest you go through this thread: [here](https://stats.stackexchange.com/questions/246862/learning-initial-state-in-rnns)
Here they have mentioned why we learn initial states.
