### ISSUE TITLE
error in training

### ISSUE THREAD

**Issue by 18463105800** [vikrant7/mobile-vod-bottleneck-lstm#7]
![image](https://user-images.githubusercontent.com/32431882/67447183-ad2b8e80-f645-11e9-9781-fb130755cbd7.png)

**Comment by vikrant7** [comment]
Hi @18463105800, please either remove extra training samples or use batch size by which the total number of samples is divisible.

**Comment by 18463105800** [comment]
> Hi @18463105800, please either remove extra training samples or use batch size by which the total number of samples is divisible.

Ok, I got it.
