### ISSUE TITLE
train_mvod_basenet.py: error: unrecognized arguments: to ILSVRC2015 root dir}

### ISSUE THREAD

**Issue by taxuewuhenxiaoer** [vikrant7/mobile-vod-bottleneck-lstm#9]
when i run the code: 
python train_mvod_basenet.py --datasets {path to ILSVRC2015 root dir} --batch_size 60 --num_epochs 30 --width_mult 1
there is an error: train_mvod_basenet.py: error: unrecognized arguments: to ILSVRC2015 root dir}
how can i solve it?

**Comment by vikrant7** [comment]
Hi @taxuewuhenxiaoer, please replace {path to ILSVRC2015 root dir} to the path to the ILSVRC2015 directory on your system.

**Comment by taxuewuhenxiaoer** [comment]
get it

**Comment by taxuewuhenxiaoer** [comment]
when i change the right path, but it has an error:
TypeError: expected str, bytes or os.PathLike object, not NoneType
why?
